GET http://localhost:8080/login HTTP/1.1

###

POST http://localhost:8080/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=test&password=test

###

GET http://localhost:8080/abc HTTP/1.1

### Żądanie do kontrolera rejestracji - powinno zwrócić treść strony rejestracji

GET http://localhost:8080/register

### Żądanie do kontrolera rejestracji - z pustymi danymi formularza

POST http://localhost:8080/register

### Żądanie do kontrolera rejestracji - z danymi

POST http://localhost:8080/register
Content-Type: application/x-www-form-urlencoded

username=u_test&password=p_test&firstName=f_test&lastName=l_test

###

POST localhost:8080/add-advert
Content-Type: application/x-www-form-urlencoded

title=Hakier&description=psuje

###

POST localhost:8080/delete-advert
Content-Type: application/x-www-form-urlencoded

advertId=4

###

POST localhost:8080/edit-advert
Content-Type: application/x-www-form-urlencoded

advertId=2&title=abc















