### Pobranie listy użytkowników

GET localhost:8080/api/users

### Pobranie listy ogłoszeń

GET localhost:8080/api/adverts

### Pobieranie konkretnego użytkownika

GET localhost:8080/api/users/2

### Pobieranie konkretnego ogłoszenia

GET localhost:8080/api/adverts/4

### Usuwanie konkretnego użytkownika

DELETE localhost:8080/api/users/4

### Usuwanie konkretnego ogłoszenia

DELETE localhost:8080/api/adverts/10